/* tslint:disable */
/* eslint-disable */
/**
 * Bid Command Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface PlaceBidRequest
 */
export interface PlaceBidRequest {
    /**
     * 
     * @type {string}
     * @memberof PlaceBidRequest
     */
    'bidderId': string;
    /**
     * 
     * @type {number}
     * @memberof PlaceBidRequest
     */
    'amount': number;
}
/**
 * 
 * @export
 * @interface PlaceBidResponse
 */
export interface PlaceBidResponse {
    /**
     * 
     * @type {string}
     * @memberof PlaceBidResponse
     */
    'bidId': string;
    /**
     * 
     * @type {string}
     * @memberof PlaceBidResponse
     */
    'auctionId': string;
    /**
     * 
     * @type {string}
     * @memberof PlaceBidResponse
     */
    'bidderId': string;
    /**
     * 
     * @type {boolean}
     * @memberof PlaceBidResponse
     */
    'accepted': boolean;
    /**
     * 
     * @type {number}
     * @memberof PlaceBidResponse
     */
    'currentPrice': number;
    /**
     * 
     * @type {number}
     * @memberof PlaceBidResponse
     */
    'minNextBid': number;
    /**
     * 
     * @type {string}
     * @memberof PlaceBidResponse
     */
    'at': string;
}
/**
 * 
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {
    /**
     * A URI reference [RFC3986] that identifies the problem type
     * @type {string}
     * @memberof ProblemDetails
     */
    'type': string;
    /**
     * A short, human-readable summary of the problem type
     * @type {string}
     * @memberof ProblemDetails
     */
    'title': string;
    /**
     * The HTTP status code generated by the origin server for this occurrence of the problem
     * @type {number}
     * @memberof ProblemDetails
     */
    'status': number;
    /**
     * A human-readable explanation specific to this occurrence of the problem
     * @type {string}
     * @memberof ProblemDetails
     */
    'detail'?: string;
    /**
     * A URI reference that identifies the specific occurrence of the problem
     * @type {string}
     * @memberof ProblemDetails
     */
    'instance'?: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Place a new bid for a given auction.   
         * @summary Place a bid on an auction
         * @param {string} auctionId ID of the auction to bid on
         * @param {PlaceBidRequest} placeBidRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BidsAuctionIdPost: async (auctionId: string, placeBidRequest: PlaceBidRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'auctionId' is not null or undefined
            assertParamExists('apiV1BidsAuctionIdPost', 'auctionId', auctionId)
            // verify required parameter 'placeBidRequest' is not null or undefined
            assertParamExists('apiV1BidsAuctionIdPost', 'placeBidRequest', placeBidRequest)
            const localVarPath = `/api/v1/bids/{auctionId}`
                .replace(`{${"auctionId"}}`, encodeURIComponent(String(auctionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(placeBidRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Place a new bid for a given auction.   
         * @summary Place a bid on an auction
         * @param {string} auctionId ID of the auction to bid on
         * @param {PlaceBidRequest} placeBidRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BidsAuctionIdPost(auctionId: string, placeBidRequest: PlaceBidRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlaceBidResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1BidsAuctionIdPost(auctionId, placeBidRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiV1BidsAuctionIdPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Place a new bid for a given auction.   
         * @summary Place a bid on an auction
         * @param {string} auctionId ID of the auction to bid on
         * @param {PlaceBidRequest} placeBidRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BidsAuctionIdPost(auctionId: string, placeBidRequest: PlaceBidRequest, options?: RawAxiosRequestConfig): AxiosPromise<PlaceBidResponse> {
            return localVarFp.apiV1BidsAuctionIdPost(auctionId, placeBidRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Place a new bid for a given auction.   
     * @summary Place a bid on an auction
     * @param {string} auctionId ID of the auction to bid on
     * @param {PlaceBidRequest} placeBidRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiV1BidsAuctionIdPost(auctionId: string, placeBidRequest: PlaceBidRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiV1BidsAuctionIdPost(auctionId, placeBidRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



