// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// PlaceBidRequest defines model for PlaceBidRequest.
type PlaceBidRequest struct {
	Amount   float64 `json:"amount"`
	BidderId string  `json:"bidderId"`
}

// PlaceBidResponse defines model for PlaceBidResponse.
type PlaceBidResponse struct {
	Accepted     bool      `json:"accepted"`
	At           time.Time `json:"at"`
	AuctionId    string    `json:"auctionId"`
	BidId        string    `json:"bidId"`
	BidderId     string    `json:"bidderId"`
	CurrentPrice float64   `json:"currentPrice"`
	MinNextBid   float64   `json:"minNextBid"`
}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	// Detail A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem type
	Title string `json:"title"`

	// Type A URI reference [RFC3986] that identifies the problem type
	Type string `json:"type"`
}

// PostApiV1BidsAuctionIdJSONRequestBody defines body for PostApiV1BidsAuctionId for application/json ContentType.
type PostApiV1BidsAuctionIdJSONRequestBody = PlaceBidRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostApiV1BidsAuctionIdWithBody request with any body
	PostApiV1BidsAuctionIdWithBody(ctx context.Context, auctionId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1BidsAuctionId(ctx context.Context, auctionId string, body PostApiV1BidsAuctionIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostApiV1BidsAuctionIdWithBody(ctx context.Context, auctionId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1BidsAuctionIdRequestWithBody(c.Server, auctionId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1BidsAuctionId(ctx context.Context, auctionId string, body PostApiV1BidsAuctionIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1BidsAuctionIdRequest(c.Server, auctionId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostApiV1BidsAuctionIdRequest calls the generic PostApiV1BidsAuctionId builder with application/json body
func NewPostApiV1BidsAuctionIdRequest(server string, auctionId string, body PostApiV1BidsAuctionIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1BidsAuctionIdRequestWithBody(server, auctionId, "application/json", bodyReader)
}

// NewPostApiV1BidsAuctionIdRequestWithBody generates requests for PostApiV1BidsAuctionId with any type of body
func NewPostApiV1BidsAuctionIdRequestWithBody(server string, auctionId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "auctionId", runtime.ParamLocationPath, auctionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/bids/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostApiV1BidsAuctionIdWithBodyWithResponse request with any body
	PostApiV1BidsAuctionIdWithBodyWithResponse(ctx context.Context, auctionId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1BidsAuctionIdResponse, error)

	PostApiV1BidsAuctionIdWithResponse(ctx context.Context, auctionId string, body PostApiV1BidsAuctionIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1BidsAuctionIdResponse, error)
}

type PostApiV1BidsAuctionIdResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON201                   *PlaceBidResponse
	ApplicationproblemJSON400 *ProblemDetails
	ApplicationproblemJSON401 *ProblemDetails
	ApplicationproblemJSON409 *ProblemDetails
	ApplicationproblemJSON422 *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r PostApiV1BidsAuctionIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1BidsAuctionIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostApiV1BidsAuctionIdWithBodyWithResponse request with arbitrary body returning *PostApiV1BidsAuctionIdResponse
func (c *ClientWithResponses) PostApiV1BidsAuctionIdWithBodyWithResponse(ctx context.Context, auctionId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1BidsAuctionIdResponse, error) {
	rsp, err := c.PostApiV1BidsAuctionIdWithBody(ctx, auctionId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1BidsAuctionIdResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1BidsAuctionIdWithResponse(ctx context.Context, auctionId string, body PostApiV1BidsAuctionIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1BidsAuctionIdResponse, error) {
	rsp, err := c.PostApiV1BidsAuctionId(ctx, auctionId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1BidsAuctionIdResponse(rsp)
}

// ParsePostApiV1BidsAuctionIdResponse parses an HTTP response from a PostApiV1BidsAuctionIdWithResponse call
func ParsePostApiV1BidsAuctionIdResponse(rsp *http.Response) (*PostApiV1BidsAuctionIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1BidsAuctionIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest PlaceBidResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Place a bid on an auction
	// (POST /api/v1/bids/{auctionId})
	PostApiV1BidsAuctionId(c *gin.Context, auctionId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostApiV1BidsAuctionId operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1BidsAuctionId(c *gin.Context) {

	var err error

	// ------------- Path parameter "auctionId" -------------
	var auctionId string

	err = runtime.BindStyledParameterWithOptions("simple", "auctionId", c.Param("auctionId"), &auctionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter auctionId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1BidsAuctionId(c, auctionId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/bids/:auctionId", wrapper.PostApiV1BidsAuctionId)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8SWb2/bthPH3wrB3+9BismS7LRdomdJimIpsCFI3RVYFgQUebaukEiVPLnOAr/3gaT8",
	"T3G6ZsCQZ7Z04n143+P3+MClaVqjQZPjxQN3soJGhJ9XtZBwjuoavnbgyD9qrWnBEkIIEI3pdHgOS9G0",
	"NfBinI/TNwmfGdsI4gVXpitr4Amn+xZ4wXXXlGD5KuElKgX2Uu19zjsH9m48Od5+4ciinvPVKuEWvnZo",
	"QfHiZvt5ssa43Xxiyi8gySfZbsG1Rjs4sAcpoSXYxyDbwWa10pgahPbLif3N8kk+eTPKT0f5eDrOi8mk",
	"OD7+g+/uXhCMCBt4vJ2Ei04SGj2sgLh7/ebtofgS1TC2vPv55PSJ2GcVN+GysxY0XVmU8C8VbVD/Bks6",
	"RzVYYPJDCzwWOKq7KVOyJ/patwH6HkbCF2AdGs2Ddgc7xJqyhuYdkMDaPe4PFV7EX05abD0ML/gZq7pG",
	"6JEFoURZA4NlWwst/GvmWpA4Q8nIMKrQMSMjpARmZowqYG3My5MdfS71QtSoWImKxaZO2DjP0zxlv6LG",
	"pmuYhiWF9+hYKOwhLVE7EjrqOKT+dH3JLMwgwlAliKECTThDcIFsA/9j0FkvkMtC52YlKpetG3Mjemfx",
	"EKkjQZ17zDmtgP0ynV6xGMCkUcDmoMEKAsXK+4BjLM5RMwd2AZbNjH1OsV8vl1si1ATz2MWEVB+snKuM",
	"pWQou+uaRtj7QSYW1t1Nd46KWfBd5/mhNt9Y02uKWlpoQNOhCsUH/6TjzfX7i+PTk7e3BxV9Eqoial2R",
	"ZfFczY1KpWmyPtxlAXPUoB7tIn5f08Ep7lPGom70fnwQfS+A7CzS/Uc/geLhK0FYsGcdVdt/79fpP3ye",
	"+hVDtPfC8HYL5PfGV6twHGbGf98rG6S4ME0jtGIfwS5QAju7utxxi4KP0zzNff1NC1q0yAt+nOapt85W",
	"UBXoMtFithjHjn/Y+NQqmIiJA3NftjCOmGAavoVD7FtWsDkuQLP++5SxP71deQ8S6/nAr4yjsxZ/H5+j",
	"cmc7jtgKKxogsI4XN8N0l+/Wbdkv7v3I5w2GiD7Eb4YnXItQw12v3aoYp2G8GIQ6DhS/jcHg6Nyoex8h",
	"jSaINwPRtjXKsJPsi/NYDztL/d/CjBf8f9n2EpL1N5BseP1Y7feWpwoP4mQPikzy8X+Qvr86hPz7Bfad",
	"tBlEq4S/zvPv5O/P1U/P5NgfUAco1mOjF4EdQTpPE9agc6jnbIZQK/cq8o1fgO+TFh1VxuJfoNjRGstY",
	"hj34h8/THu/0BfAujJ7VKIkdmY5GZjbytzbWW4HHVF2EgAg5mbwA5N74OHpifiSbcy5r40AlDEimr/bc",
	"NdjErq/e3PoD3I+xHY+KPsHExpkiVhy20W06W/dGW2RZbaSoK+OoOMlPJnx1u/o7AAD///phAM9bDAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
